### PR TITLE
Feature/expansion hooks

### PR DESCRIPTION
**Pull request by menno-ll**
## Description

Fixes https://github.com/publishpress/PublishPress-Future/issues/324

As requested in the issue above, this Pull Request adds some customization options to te plugin, using filters.
It allows for customizing the email that is sent when a post expires (subject, body, email addresses, headers and attachments), and it allows customizing templates that are rendered by the plugin (both the arguments and the template files).

> ❗ Because I installed this plugin also via composer to test my changes with (our theme that wants to use this feature also uses composer), both this plugin and our theme shared the same dependency `psr/container`. This resulted in a conflict, as the version number for this plugin was forced to `1.0.0`, while one of our theme dependencies required `^1.1`. I've changed the required version of this plugin to be `^1.0`, so the conflict is gone. However, if you know that this causes another issue that I don't know of, please feel free to tell me and I will undo this change.

## Benefits

These changes allow developers to alter the behavior of e-mails and templates.
They are now able to add more of their own customizations to it and use this plugin, instead of creating their own solution from scratch.
So easier for devs, and more plugin installs for you :).

## Possible drawbacks

Unskilled developers can in theory also use these filters, which could lead to more support request if used incorrectly.
Also, if an update is created for this plugin, which changes the behavior of for example one of the templates, the developer that made modifications might need to change their code as well.

## Applicable issues

Fixes https://github.com/publishpress/PublishPress-Future/issues/324

## Checklist

- [x] I have created a specific branch for this pull request before committing, starting off the current HEAD of `development` branch. 
- [x] I'm submitting to the `development`, feature/hotfix/release branch. (Do not submit to the master branch!)
- [x] This pull request relates to a specific problem (bug or improvement).
- [x] I have mentioned the issue number in the pull request description text.
- [x] All the issues mentioned in this pull request relate to the problem I'm trying to solve.
- [x] The code I'm sending follows the [PSR-12](https://www.php-fig.org/psr/psr-12/) coding style.

### CODE REVIEW

**Comment by menno-ll** [comment]
Dear @andergmartins 
Here is the PR with the filters I requested.
It contains:

- 5 brand new filters to customize the email that is sent when content expires
- 2 filters for customizing template rendering. One to change the template file that is included, and another to change the parameters that are available in that template.
(I've chosen this option, as i think it's the most clean option for your plugin. After thinking about it, adding actions inside the template of this plugin to allow for custom behavior was not the way to go. That would just be dirty. If a developer (in this case me) wants to add some items to for example your metabox, I think that it's better if i create my own metabox instead of abusing the one of this plugin.)

**Comment by stevejburge** [comment]
Thanks for this @menno-ll. We'll review in time for the first release of 2023

**Review by andergmartins — APPROVED** [review]

**Comment by andergmartins** [comment]
@menno-ll Thanks, I'm approving this but I will revert the `psr/container` strict version for now, until we can drop PHP 5 support.

**Comment by menno-ll** [comment]
@andergmartins 
Please note that because of the updated psr/container you will also need to revert the changes in the composer.lock file.

**Pull request merged**
