### PR TITLE
Release v2.4.2

### PR DESCRIPTION
**Pull request by andergmartins**
Hi, @contactashish13 here are the changes I did before releasing on WordPress.org. Please, let me know if you have any questions.

### CODE REVIEW

**Review by contactashish13 — APPROVED** [review]
@andergmartins thanks! this looks good.

**Comment by contactashish13** [comment]
@andergmartins is this still relevant as 2.4.2 was released?

**Comment by contactashish13** [comment]
@stevejburge is this still relevant or can we close this?

**Comment by stevejburge** [comment]
@contactashish13 We can close, but let's take note of these steps for the next release

**Pull request closed without merging**
